name: Water Data Export

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour at minute 00 (UTC)
  workflow_dispatch:       # allow manual run

jobs:
  export-water-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run water export script
        run: |
          python water_export_cli.py

      - name: Commit and push CSV if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add data/water_data_full_combined.csv || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "Update water data CSV [skip ci]"
          git push
